version: "3"
services:
  frontend:
    build:      
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    hostname: frontend
    tty: true
    environment:
      - WATCHPACK_POLLING=true
      - STATUS=development
    ports:
      - 3000:3000
    volumes:
      - ./frontend/app:/usr/src/app

  backend:
    build:      
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend
    hostname: backend
    environment:
      FLASK_ENV: "development"
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 5000:5000
    volumes:
      - ./backend/app:/usr/src/app

  db:
    image: mysql:latest
    container_name: db
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: flask-app
      MYSQL_USER: flask
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
    - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: 'db'
    ports:
    - 8080:80

volumes:
  mysql-data:
